const products = [
  { name: "Coco Mademoiselle CHANEL", category: "perfume", price: 2500 },
  { name: "Victoria's Secret Bombshell", category: "perfume", price: 3000 },
  { name: "KAYALI Vanille", category: "perfume", price: 3000 },
  { name: "KAYALI Fruit Rouge", category: "perfume", price: 3000 },
  { name: "Prada MILANO", category: "perfume", price: 3500 },
  { name: "LIBRE", category: "perfume", price: 5000 },
  { name: "BURBURRY HER", category: "perfume", price: 3500 },

  { name: "Fond de teint NARS", category: "makeup", price: 200 },
  { name: "Mascara ESSENCE", category: "makeup", price: 50 },
  { name: "Ensemble de brosse Make up de REDSQUARE", category: "makeup", price: 250 },
  { name: "4 Gloss RHODE", category: "makeup", price: 350 },
  { name: "3 Rouge a lévres MAYBELLINE", category: "makeup", price: 300 },
  { name: "Mascara SKY HIGH", category: "makeup", price: 80 },
  { name: "7 Rouge a lévres RARE BEAUTY", category: "makeup", price: 250 },
  { name: "Pallette Nude de NARS", category: "makeup", price: 1000 },
  { name: "Eylener DIOR", category: "makeup", price: 150 },
  { name: "4 Beauty Blinder", category: "makeup", price: 250 },
  { name: "6 Blush DIOR", category: "makeup", price: 2500 },
  { name: "Démaquillant GARNIER", category: "makeup", price: 150 },

  { name: "Pack de DOVE", category: "skincare", skin: "oily", price: 2000 },
  { name: "Pack CENTELLA", category: "skincare", skin: "sensitive", price: 3500 },
  { name: "CERAVE, La Roche-Posay, Vaseline", category: "skincare", skin: "dry", price:2500 },
  { name: "Petit pack CENTELLA", category: "skincare", skin: "oily", price: 2000 },
  { name: "3 Créme de Beauty Of Joseon", category: "skincare", skin: "sensitive", price: 1500 },
  { name: "Pack ORDINARY", category: "skincare", skin: "dry", price: 2500 },
  { name: "Pack DOVE Noix de coco", category: "skincare", skin: "oily", price: 3500 },
  { name: "Glow Recipe", category: "skincare", skin: "oily", price: 3000 },
  { name: "Pack MEDICUBE", category: "skincare", skin: "sensitive", price: 4500 },
  { name: "Serum péche ANUA", category: "skincare", skin: "dry", price: 5000 },
  { name: "Pack DIOR", category: "skincare", skin: "dry", price: 2000 },
  { name: "Pack Shampoing MIEL", category: "skincare", skin: "sensitive", price: 2500 },

  { name: "Grande pack LANEIGE", category: "box", price: 3000 },
  { name: "Grande pack CENTELLA", category: "box", price: 3500 },

];